### ISSUE TITLE
Minecraft source code

### ISSUE THREAD

**Issue by Keridos** [SuperStarGamesNetwork/IronManMod#2]
You should really remove the source code of minecraft from this repo.

**Comment by punchball** [comment]
Who is this?

Chris Zelley

**Comment by Keridos** [comment]
You are aware that Mojang can sue you for including minecraft source code in here?

**Comment by punchball** [comment]
I'm not part of this mod... My 2 friends made it and are SuperStarGamesNetwork, I just put my email down on it a few years ago... 

Chris Zelley

**Comment by R3alCl0ud** [comment]
this was a working repository in which i developed the mod, so i was working out of the source code, also this is not the actual minecraft source, it is a decompiled version of the minecraft forge mod loader source, this is not breaking any of the eula as it is not the officail source of minecraft, and the code is all open source
